'use client';

import { useEffect, useState, type FormEvent, type ReactNode } from 'react';
import Link from 'next/link';
import Image from 'next/image';
import { useRouter } from 'next/navigation';
import * as Dialog from '@radix-ui/react-dialog';
import { QRCodeSVG } from 'qrcode.react';
import { ArrowClockwise, ArrowDown, ArrowLeft, ArrowRight, ArrowUpRight, Bag, CalendarBlank, CaretDown, CaretRight, Check, CheckCircle, Clock, Copy, Crown, DeviceMobile, DownloadSimple, Gift, Heart, House, Info, Moon, QrCode, Receipt, ShieldCheck, SignOut, Sparkle, Sun, WarningCircle, X } from '@phosphor-icons/react';
import { dateLabel, number, rupiah } from '@/lib/format';
import type { PageData } from '@/lib/load';
import type { Member, Transaction } from '@/lib/types';
import { redemptionOptions, terms } from '@/lib/terms';

type Page = 'home' | 'history' | 'info';
type InstallPrompt = Event & { prompt: () => Promise<void>; userChoice: Promise<{ outcome: string }> };
const navigation = [{ href: '/', label: 'Beranda', icon: House, page: 'home' }, { href: '/riwayat', label: 'Riwayat poin', icon: Clock, page: 'history' }, { href: '/info', label: 'Info penukaran', icon: Gift, page: 'info' }];
const initials = (name: string) => name.split(/\s+/).slice(0, 2).map(word => word[0] ?? '').join('').toUpperCase() || 'B';
/** Months offered by the history filter: the current month and the eleven before it. */
function monthOptions() { const now = new Date(); return Array.from({ length: 12 }, (_, index) => { const date = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth() - index, 1)); return { value: date.toISOString().slice(0, 7), label: new Intl.DateTimeFormat('id-ID', { month: 'long', year: 'numeric', timeZone: 'UTC' }).format(date) }; }); }

export function Brand({ light = false }: { light?: boolean }) { return <span className={`brand ${light ? 'brand-light' : ''}`}><Image className="brand-symbol" src="/logo.png" alt="" width={591} height={548} sizes="44px" /><span className="brand-type">beauty<span>KENDARI</span></span></span>; }
function Modal({ open, setOpen, title, description, children }: { open: boolean; setOpen: (open: boolean) => void; title: string; description: string; children: ReactNode }) { return <Dialog.Root open={open} onOpenChange={setOpen}><Dialog.Portal><Dialog.Overlay className="modal-overlay" /><Dialog.Content className="modal-content"><Dialog.Close className="icon-button modal-close" aria-label="Tutup"><X size={21} /></Dialog.Close><Dialog.Title>{title}</Dialog.Title><Dialog.Description>{description}</Dialog.Description>{children}</Dialog.Content></Dialog.Portal></Dialog.Root>; }
function ThemeButton() { const [dark, setDark] = useState(false); useEffect(() => { const value = localStorage.getItem('beauty-theme'); const next = value ? value === 'dark' : window.matchMedia('(prefers-color-scheme: dark)').matches; setDark(next); document.documentElement.dataset.theme = next ? 'dark' : 'light'; }, []); return <button className="icon-button theme-button" aria-label={dark ? 'Aktifkan mode terang' : 'Aktifkan mode gelap'} onClick={() => { setDark(!dark); document.documentElement.dataset.theme = dark ? 'light' : 'dark'; localStorage.setItem('beauty-theme', dark ? 'light' : 'dark'); }}>{dark ? <Sun size={21} /> : <Moon size={21} />}</button>; }

export function BeautyApp({ page, data }: { page: Page; data: PageData }) {
 const { member, transactions, demo, historyFailed } = data;
 const router = useRouter();
 const [qrOpen, setQrOpen] = useState(false); const [helpOpen, setHelpOpen] = useState(false); const [accountOpen, setAccountOpen] = useState(false); const [installOpen, setInstallOpen] = useState(false); const [installPrompt, setInstallPrompt] = useState<InstallPrompt | null>(null); const [installed, setInstalled] = useState(false); const [copied, setCopied] = useState(false); const [selection, setSelection] = useState<Transaction | null>(null);
 useEffect(() => { if ('serviceWorker' in navigator) navigator.serviceWorker.register('/sw.js').catch(() => {}); const handler = (event: Event) => { event.preventDefault(); setInstallPrompt(event as InstallPrompt); }; const onInstalled = () => { setInstalled(true); setInstallPrompt(null); }; window.addEventListener('beforeinstallprompt', handler); window.addEventListener('appinstalled', onInstalled); setInstalled(window.matchMedia('(display-mode: standalone)').matches); return () => { window.removeEventListener('beforeinstallprompt', handler); window.removeEventListener('appinstalled', onInstalled); }; }, []);
 async function copyCard() { try { await navigator.clipboard.writeText(member.card); setCopied(true); } catch { setCopied(false); } }
 async function install() { if (installPrompt) { await installPrompt.prompt(); const choice = await installPrompt.userChoice; if (choice.outcome === 'accepted') setInstalled(true); setInstallPrompt(null); } else setInstallOpen(true); }
 async function logout() { try { await fetch('/api/logout', { method: 'POST' }); } finally { router.replace('/login'); router.refresh(); } }
 return <div className={`app-shell ${page === 'home' ? 'home-page' : page === 'history' ? 'history-page' : 'info-page'}`}>
  <aside className="sidebar"><Link href="/" aria-label="Beauty Kendari beranda"><Brand /></Link><div className="sidebar-label">RUANG MEMBER</div><nav aria-label="Navigasi utama">{navigation.map(item => <Link key={item.page} href={item.href} className={`nav-link ${page === item.page ? 'active' : ''}`} aria-current={page === item.page ? 'page' : undefined}><item.icon size={22} weight={page === item.page ? 'fill' : 'regular'} /><span>{item.label}</span>{page === item.page && <span className="nav-active-mark" />}</Link>)}</nav><div className="sidebar-bottom"><div className="pocket-card"><span className="pocket-icon"><DeviceMobile size={26} /></span><h3>Beauty, selalu dekat.</h3><p>Akses kartu member langsung dari layar utama HP.</p><button className="button secondary small" onClick={install} disabled={installed}><DownloadSimple size={17} />{installed ? 'Sudah terpasang' : 'Pasang aplikasi'}</button></div><button className="help-link" onClick={() => setHelpOpen(true)}><Info size={20} />Butuh bantuan?<ArrowUpRight size={16} /></button><div className="sidebar-account"><span className="avatar">{initials(member.name)}</span><span><strong>{member.name}</strong><small>Beauty member</small></span><button className="icon-button" onClick={logout} aria-label="Keluar"><SignOut size={21} /></button></div></div></aside>
  <div className="workspace"><header className="topbar"><span className="desktop-breadcrumb">Member area <CaretRight size={14} /><strong>{page === 'home' ? 'Beranda' : page === 'history' ? 'Riwayat poin' : 'Info penukaran'}</strong></span><Link href="/" className="mobile-brand" aria-label="Beauty Kendari"><Brand /></Link><div className="header-actions">{demo && <Link href="/login" className="demo-label">Data demo <ArrowUpRight size={13} /></Link>}<ThemeButton /><span className="header-divider" /><button className="avatar small-avatar account-button" onClick={() => setAccountOpen(true)} aria-label="Akun dan pengaturan">{initials(member.name)}</button></div></header>
  <main id="main-content"><div className="page-heading"><div><div className="greeting">{page === 'home' ? 'RUANG MEMBER' : 'BEAUTY MEMBER'}</div><h1>{page === 'home' ? <>Halo, {member.firstName}! <Sparkle className="heading-sparkle" weight="duotone" /></> : page === 'history' ? 'Riwayat poin' : 'Info penukaran'}</h1><p>{page === 'home' ? 'Kartu member dan poin, selalu dekat denganmu.' : page === 'history' ? 'Pantau poin masuk dan penukaranmu.' : 'Pilih nilai penukaran, lalu tunjukkan kartu ke kasir.'}</p></div>{member.since && <span className="member-since"><Heart size={17} />Member sejak {member.since}</span>}</div>
  {page === 'home' ? <><section className="overview-grid" aria-label="Kartu dan saldo member"><div className="membership-wrap"><div className="membership-card"><Heart className="card-heart heart-one" weight="thin" /><Heart className="card-heart heart-two" weight="thin" /><div className="card-top"><Brand light /><span className="gold-label"><Crown size={17} weight="fill" />{member.tier} MEMBER</span></div><div className="card-bottom"><div><span className="card-label">YOUR BEAUTY MEMBERSHIP</span><h2>{member.name}</h2><button className="card-number" aria-label="Salin nomor kartu" onClick={copyCard}>{member.card}<Copy size={15} /></button></div><button className="card-qr" onClick={() => setQrOpen(true)} aria-label="Perbesar QR kartu member"><QRCodeSVG value={member.card} size={66} marginSize={2} /><span><QrCode size={12} />Lihat QR</span></button></div><div className="card-footer"><span>Teman perjalanan cantikmu.</span><span>beauty member</span></div></div><div className="card-validity"><span><ShieldCheck size={17} />{member.expires ? <>Kartu aktif sampai <strong>{member.expires}</strong></> : 'Tanggal berakhir kartu belum tersedia'}</span><span className="copy-feedback" aria-live="polite">{copied ? 'Nomor tersalin' : ''}</span></div></div>
  <div className="points-card"><div className="points-top"><span className="label-icon"><span className="circle-icon"><Sparkle size={21} weight="duotone" /></span>Saldo poin kamu</span><span className="status-pill"><CheckCircle size={14} weight="fill" />Aktif</span></div><div className="point-number">{number(member.points)}<span>poin</span></div><div className="points-divider" /><div className="points-note"><Gift size={22} /><span><strong>100 poin = Rp10.000</strong><br />Tukar langsung di kasir outlet.</span></div><Link href="/info" className="text-link">Cara menggunakan poin <ArrowRight size={18} /></Link></div></section>
  <section className="lower-grid"><History compact demo={demo} failed={historyFailed} transactions={transactions} onSelect={setSelection} /><div className="right-column"><div className="beauty-banner"><Image src="/beauty-still-life.webp" alt="Koleksi skincare dan kosmetik bernuansa pink" fill sizes="(max-width: 767px) 100vw, 400px" priority /><div className="banner-copy"><span>UNTUK DIRIMU</span><h2>Cantikmu,<br /><em>lebih berarti.</em></h2><Link href="/info">Lihat pilihan penukaran <ArrowUpRight size={17} /></Link></div></div><button className="outlet-note" onClick={() => setHelpOpen(true)}><span className="circle-icon"><Heart size={22} /></span><span><strong>Kami siap bantu kamu</strong><small>Tanyakan langsung ke tim outlet.</small></span><ArrowUpRight size={19} /></button></div></section></> : page === 'history' ? <History demo={demo} failed={historyFailed} transactions={transactions} onSelect={setSelection} /> : <InfoPage onQr={() => setQrOpen(true)} />}
  <footer className="page-footer"><span>© {new Date().getFullYear()} Beauty Kendari</span><span>Dibuat untuk perjalanan cantikmu <Heart size={13} /></span></footer></main>
  </div><nav className="mobile-nav" aria-label="Navigasi ponsel">{navigation.map(item => <Link key={item.page} href={item.href} className={page === item.page ? 'active' : ''} aria-current={page === item.page ? 'page' : undefined}><item.icon size={22} weight={page === item.page ? 'fill' : 'regular'} /><span>{item.label}</span></Link>)}</nav>
  <Modal open={qrOpen} setOpen={setQrOpen} title="Kartu member kamu" description="Tunjukkan QR ini kepada kasir Beauty Kendari."><div className="large-qr"><QRCodeSVG value={member.card} size={220} marginSize={4} level="M" title={`Nomor kartu ${member.card}`} /></div><div className="qr-details"><strong>{member.name}</strong><span>{member.card}</span>{demo && <span className="demo-disclaimer">Kartu contoh. Bukan kartu member asli.</span>}</div><button className="button primary full" onClick={copyCard}>{copied ? <Check size={19} /> : <Copy size={19} />}{copied ? 'Nomor tersalin' : 'Salin nomor kartu'}</button></Modal>
  <Modal open={helpOpen} setOpen={setHelpOpen} title="Ada yang bisa kami bantu?" description="Tim kasir dan CS Beauty Kendari siap membantu saat kamu berkunjung ke outlet."><div className="help-content"><Info size={26} /><p>Siapkan nomor kartu <strong>{member.card}</strong> dan bukti transaksi untuk pertanyaan seputar saldo atau data member.</p></div><p className="muted">Kontak dan alamat resmi outlet akan ditambahkan setelah dikonfirmasi tim Beauty Kendari.</p><Link className="button primary full" href="/info" onClick={() => setHelpOpen(false)}>Baca info penukaran <ArrowRight size={18} /></Link></Modal>
  <Modal open={installOpen} setOpen={setInstallOpen} title="Beauty di layar utamamu" description="Buka aplikasi lebih cepat tanpa mengetik alamat website."><div className="install-instructions"><h3>iPhone / iPad</h3><p>Buka melalui Safari, ketuk Bagikan, lalu pilih Tambahkan ke Layar Utama.</p><h3>Android / desktop</h3><p>Buka menu browser, pilih Instal aplikasi atau Tambahkan ke layar utama. Opsi muncul jika browser mendukung dan situs diakses lewat HTTPS.</p></div></Modal>
  <Modal open={accountOpen} setOpen={setAccountOpen} title="Akun kamu" description="Kartu member, pemasangan aplikasi, dan keluar dari sesi ini."><div className="account-identity"><span className="avatar">{initials(member.name)}</span><span><strong>{member.name}</strong><small>{member.tier} member · {member.card}</small></span></div><div className="account-actions"><button onClick={() => { setAccountOpen(false); void install(); }} disabled={installed}><DownloadSimple size={20} /><span>{installed ? 'Aplikasi sudah terpasang' : 'Pasang aplikasi'}</span><CaretRight size={15} /></button><button onClick={() => { setAccountOpen(false); setHelpOpen(true); }}><Info size={20} /><span>Butuh bantuan?</span><CaretRight size={15} /></button></div><button className="button secondary full account-logout" onClick={logout}><SignOut size={19} />Keluar</button></Modal>
  <Modal open={selection !== null} setOpen={open => { if (!open) setSelection(null); }} title="Detail transaksi" description={selection ? dateLabel(selection.date) : ''}>{selection && <><div className="transaction-detail"><span className="circle-icon"><Receipt size={28} /></span><h3>{selection.title}</h3><strong className={selection.points > 0 ? 'positive' : ''}>{selection.points > 0 ? '+' : ''}{number(selection.points)} poin</strong></div><dl className="detail-list"><div><dt>No. transaksi</dt><dd>{selection.id}</dd></div><div><dt>Outlet</dt><dd>{selection.outlet}</dd></div><div><dt>Nominal belanja</dt><dd>{selection.amount ? rupiah(selection.amount) : 'Tidak berlaku'}</dd></div></dl>{demo && <p className="demo-disclaimer">Data transaksi contoh untuk pratinjau frontend.</p>}</>}</Modal>
 </div>;
}

function History({ compact = false, demo, failed, transactions, onSelect }: { compact?: boolean; demo: boolean; failed: boolean; transactions: Transaction[]; onSelect: (transaction: Transaction) => void }) {
 const router = useRouter();
 const [filter, setFilter] = useState('all'); const [month, setMonth] = useState('all'); const [visible, setVisible] = useState(5);
 const filtered = transactions.filter(t => (filter === 'all' || (filter === 'in' ? t.points > 0 : t.points < 0)) && (month === 'all' || t.date.startsWith(month)));
 const shown = filtered.slice(0, compact ? 4 : visible);
 const filtersActive = filter !== 'all' || month !== 'all';
 return <section className={`history-panel ${compact ? 'compact-history' : 'full-history'}`} aria-label="Riwayat poin"><div className="section-heading"><div><h2>{compact ? 'Aktivitas terbaru' : 'Aktivitas poin'}</h2><p>{compact ? 'Empat transaksi poin terakhir.' : demo ? 'Semua aktivitas di bawah merupakan data contoh.' : 'Poin masuk dan keluar dari transaksimu di outlet.'}</p></div>{compact && <Link href="/riwayat" className="text-link">Lihat semua <ArrowRight size={16} /></Link>}</div>{!compact && <div className="history-controls"><div className="filter-tabs" aria-label="Filter jenis transaksi">{[{ value: 'all', text: 'Semua' }, { value: 'in', text: 'Poin masuk' }, { value: 'out', text: 'Poin keluar' }].map(item => <button key={item.value} className={filter === item.value ? 'selected' : ''} aria-pressed={filter === item.value} onClick={() => { setFilter(item.value); setVisible(5); }}>{item.text}</button>)}</div><label className="month-select"><CalendarBlank size={16} /><span className="sr-only">Filter bulan</span><select value={month} onChange={e => { setMonth(e.target.value); setVisible(5); }}><option value="all">Semua bulan</option>{monthOptions().map(option => <option key={option.value} value={option.value}>{option.label}</option>)}</select><CaretDown size={12} /></label></div>}
 {failed ? <div className="empty-state error-state" role="alert"><WarningCircle size={35} /><h3>Riwayat poin gagal dimuat</h3><p>Saldo dan kartumu tetap benar. Riwayat transaksi belum bisa diambil dari server.</p><button className="button secondary small" onClick={() => router.refresh()}><ArrowClockwise size={16} />Coba lagi</button></div>
 : <><div className="transaction-list">{shown.length ? shown.map((t, index) => <button className="transaction-row" key={`${t.id}-${index}`} onClick={() => onSelect(t)}><span className={`transaction-icon ${t.points < 0 ? 'spent' : ''}`}>{t.points > 0 ? <Bag size={21} /> : <Gift size={21} />}</span><span className="transaction-info"><strong>{t.title}</strong><small>{dateLabel(t.date)}<span className="transaction-amount"> · {t.amount ? rupiah(t.amount) : 'Penukaran di outlet'}</span></small></span><span className={`transaction-points ${t.points > 0 ? 'positive' : ''}`}>{t.points > 0 ? '+' : ''}{number(t.points)}<small>poin</small></span><CaretRight className="transaction-chevron" size={15} /></button>) : <div className="empty-state"><Receipt size={35} /><h3>Belum ada riwayat transaksi</h3><p>{filtersActive ? 'Tidak ada transaksi pada filter ini.' : 'Transaksi poinmu akan muncul di sini setelah belanja di outlet.'}</p>{filtersActive && <button className="text-link" onClick={() => { setFilter('all'); setMonth('all'); }}>Tampilkan semua transaksi</button>}</div>}</div>{!compact && filtered.length > visible && <button className="button secondary load-more" onClick={() => setVisible(visible + 5)}>Muat lebih banyak <ArrowDown size={17} /></button>}</>}
 {!compact && <div className="history-footnote"><Info size={14} />Penukaran poin dilakukan langsung di kasir outlet.</div>}</section>;
}
function InfoPage({ onQr }: { onQr: () => void }) { return <div className="info-layout"><div><section className="redemption-panel" aria-labelledby="redemption-title"><span className="circle-icon"><Gift size={24} /></span><h2 id="redemption-title">Pilihan penukaran poin</h2><p>Tukar poinmu saat berbelanja langsung di outlet.</p><table className="redemption-table"><caption className="sr-only">Jumlah poin dan nilai penukaran</caption><thead><tr><th scope="col">Poin ditukar</th><th scope="col">Nilai penukaran</th></tr></thead><tbody>{redemptionOptions.map(option => <tr key={option.points}><th scope="row">{number(option.points)} <span>poin</span></th><td>{rupiah(option.value)}</td></tr>)}</tbody></table><span className="redemption-note"><Info size={16} />Penukaran diproses oleh kasir dengan kartu membermu.</span></section><section className="faq-section"><h2>Yang perlu kamu tahu</h2>{terms.map((term, i) => <details key={term.title} open={i === 0}><summary>{term.title}<CaretDown size={19} /></summary><p>{term.text}</p></details>)}</section></div><aside className="info-aside"><span className="circle-icon"><Gift size={29} /></span><h2>Siap menukar poin?</h2><p>Tunjukkan kartu membermu saat berbelanja. Kasir akan membantu penukarannya.</p><button className="button primary full" onClick={onQr}><QrCode size={20} />Tampilkan kartu</button><div className="simple-steps"><span><CheckCircle size={18} />Datang ke outlet</span><span><CheckCircle size={18} />Tunjukkan kartu member</span><span><CheckCircle size={18} />Konfirmasi penukaran ke kasir</span></div></aside></div>; }

export function Login({ demo, notice, sample }: { demo: boolean; notice?: string; sample?: Member }) {
 const router = useRouter(); const [input, setInput] = useState(''); const [error, setError] = useState(notice ?? ''); const [loading, setLoading] = useState(false);
 async function submit(event: FormEvent) {
  event.preventDefault(); setError('');
  if (!input.trim()) { setError('Masukkan nomor HP atau nomor kartu terlebih dahulu.'); return; }
  setLoading(true);
  try {
   const response = await fetch('/api/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ value: input.trim() }) });
   const body = (await response.json()) as { ok?: boolean; error?: string };
   if (!response.ok || !body.ok) { setError(body.error ?? 'Gagal masuk. Coba lagi sebentar lagi.'); setLoading(false); return; }
   router.replace('/'); router.refresh();
  } catch { setError('Tidak bisa terhubung. Periksa koneksi internetmu lalu coba lagi.'); setLoading(false); }
 }
 return (
  <div className="login-page">
   <header className="login-top">
    <Link href="/" aria-label="Beauty Kendari"><Brand /></Link>
    <div className="login-top-actions">
     {demo && <Link href="/" className="text-link">Lihat demo <ArrowUpRight size={15} /></Link>}
     <ThemeButton />
    </div>
   </header>
   <section className="login-visual" aria-label="Beauty Kendari">
    <Image src="/beauty-still-life.webp" alt="Koleksi skincare dan kosmetik Beauty Kendari" fill priority sizes="(max-width: 899px) 100vw, 48vw" />
    <div className="login-intro">
     <span className="login-eyebrow">SEBUAH RUANG UNTUK DIRIMU</span>
     <h2>Cantikmu,<br /><em>begitu berarti.</em></h2>
     <p>Hal baik dimulai dari merawat diri.</p>
    </div>
   </section>
   <section className="login-form-section" aria-labelledby="login-title">
    <div className="login-form-wrap">
     <span className="login-form-eyebrow">BEAUTY MEMBER</span>
     <h1 id="login-title">Selamat datang.</h1>
     <p className="login-description">Kartu dan poin membermu, dalam satu tempat.</p>
     <form onSubmit={submit} aria-busy={loading}>
      <label htmlFor="member-number">Nomor HP atau nomor kartu</label>
      <input id="member-number" name="member-number" inputMode="numeric" autoComplete="tel" placeholder="Masukkan nomor terdaftar" value={input} onChange={e => { setInput(e.target.value); setError(''); }} aria-invalid={!!error} aria-describedby={error ? 'login-error' : 'login-helper'} disabled={loading} />
      <small id="login-helper">Gunakan nomor yang terdaftar di Beauty Kendari.</small>
      {error && <p id="login-error" className="form-error" role="alert"><WarningCircle size={17} />{error}</p>}
      <button className="button primary full" disabled={loading}>{loading ? 'Memeriksa nomor…' : 'Masuk'}{!loading && <ArrowRight size={19} />}</button>
     </form>
     <span className="login-assurance"><ShieldCheck size={15} />Masuk praktis, tanpa password.</span>
     {demo && sample && <div className="demo-login"><Info size={19} /><div><strong>Pratinjau frontend</strong><p>Belum terhubung ke data member asli.</p><button type="button" className="text-link" onClick={() => { setInput(sample.phone); setError(''); }}>Gunakan nomor demo <Copy size={14} /></button></div></div>}
     <p className="registration-note">Belum menjadi member?<span>Daftar langsung di kasir outlet Beauty Kendari.</span></p>
    </div>
    <footer className="login-footer">© {new Date().getFullYear()} Beauty Kendari</footer>
   </section>
  </div>
 );
}
